# Node.js with Vue
# Build a Node.js project that uses Vue.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  name: Default
  demands:
   - agent.name -equals agent007 

steps:
- script: |
    echo "hello"
  displayName: 'npm install and build'
